<a href="https://colab.research.google.com/github/dlsun/pods/blob/master/Chapter_01_The_Data_Ecosystem/Chapter_1.3_Rows_and_the_Observational_Unit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rows and the Observational Unit

Recall that the rows of a tabular data set represent observations. Whenever you encounter a new (tabular) data 
set, the first question you should ask yourself is

> "What is the observational unit?"

In other words, what does each row of the 
`DataFrame` represent? In the case of 
the OKCupid data set in the previous section, the observational unit was clearly an OKCupid user. But it is not always so obvious what the observational unit is.

For example, consider the Framingham Heart Study data set, which is available at https://dlsun.github.io/pods/data/framingham_long.csv. 
This data comes from a study of men and women in 
the town of Framingham, Massachusetts, which has enrolled 
thousands of patients since it began in 1948 and is still ongoing. The goal of the study is to identify risk factors for cardivascular disease (CVD) by following the subjects over time. The data set that we will analyze was collected on 4,434 subjects between 1956 and 1968. A description of the data set is available [here](https://biolincc.nhlbi.nih.gov/media/teachingstudies/FHS_Teaching_Longitudinal_Data_Documentation_2021a.pdf).

You might guess that the observational unit is a subject. Let's see if that guess is correct.

In [0]:
import pandas as pd

data_dir = "https://dlsun.github.io/pods/data/"
df_framingham = pd.read_csv(data_dir + "framingham_long.csv")
df_framingham.head()

RANDID  SEX  TOTCHOL  AGE  ...  TIMESTRK  TIMECVD  TIMEDTH  TIMEHYP
0    2448    1    195.0   39  ...      8766     6438     8766     8766
1    2448    1    209.0   52  ...      8766     6438     8766     8766
2    6238    2    250.0   46  ...      8766     8766     8766     8766
3    6238    2    260.0   52  ...      8766     8766     8766     8766
4    6238    2    237.0   58  ...      8766     8766     8766     8766

[5 rows x 39 columns]

Each `RANDID` corresponds to a unique subject in the study, but each subject appears multiple times in the data set. That is because this is a longitudinal study; each subject was measured at multiple points during their lifetime. So the observational unit in the Framingham Heart Study data set is a _measurement_ of a subject at a point in time.

If there is a variable or a set of variables in the data set that uniquely identifies the observational unit, then it is customary to make those variables the index of the `DataFrame`. In the Framingham data set, `RANDID` and `TIME` uniquely identify the observational unit, so we move these columns to the index. (Notice that we specify `inplace=True` so that `.set_index()` modifies the existing `DataFrame` rather than returning a new one.)

In [0]:
df_framingham.set_index(["RANDID", "TIME"], inplace=True)
df_framingham.head()

SEX  TOTCHOL  AGE  SYSBP  ...  TIMESTRK  TIMECVD  TIMEDTH  TIMEHYP
RANDID TIME                            ...                                     
2448   0       1    195.0   39  106.0  ...      8766     6438     8766     8766
       4628    1    209.0   52  121.0  ...      8766     6438     8766     8766
6238   0       2    250.0   46  121.0  ...      8766     8766     8766     8766
       2156    2    260.0   52  105.0  ...      8766     8766     8766     8766
       4344    2    237.0   58  108.0  ...      8766     8766     8766     8766

[5 rows x 37 columns]

## Selecting Rows

We can select an individual row from a `DataFrame` using its label in the index. For example, the fourth row in the Framingham data set above has label `(6238, 2156)`. The `.loc` attribute of the `DataFrame` is used to select a row by its label. 

In [0]:
row = df_framingham.loc[(6238, 2156)]
row

We can also select a row by its position using the `.iloc` attribute. Keeping in mind that the first row is actually row 0, the fourth row could also be extracted as:

In [0]:
df_framingham.iloc[3]

Notice that a single row from a `DataFrame` is no longer a `DataFrame` but a different data structure, called a `Series`.

In [0]:
type(row)

We can also select multiple rows by passing a _list_ of labels or positions to `.loc` and `.iloc`, respectively.

In [0]:
rows = df_framingham.loc[[(2448, 4628), (6238, 2156)]]
rows

In [0]:
df_framingham.iloc[[1, 3]]

Notice that when we select multiple rows, we get a `DataFrame` back.

In [0]:
type(rows)

So a `Series` is used to store a single observation (across multiple variables), while a `DataFrame` is used to store multiple observations (across multiple variables).

If selecting consecutive rows, we can use Python's `slice` notation. For example, the code below selects all rows from the fourth row, up to (but not including) the tenth row.

In [0]:
df_framingham.iloc[3:9]

## Exercises





1\. Suppose you want to extract just the fourth row from the Framingham data set, but you want the result to be a `DataFrame` instead of a `Series`. In other words, you want a `DataFrame` with a single row. Can you figure out how to accomplish this?

In [0]:
# YOUR CODE HERE

Questions 2-4 deal with the Titanic data set (https://dlsun.github.io/pods/data/titanic.csv) contains information about 2206 passengers and crew members that were aboard the RMS Titanic when it sank on April 15, 1912.

2\. Read in the Titanic data set. What is the observational unit?

In [0]:
# YOUR CODE HERE

3\. What column seems to be appropriate index for this data set? Do you see any problems with using this column as the index? (_Hint:_ Try looking up "Kelly, Mr. James" in this [passenger list](https://en.wikipedia.org/wiki/Passengers_of_the_Titanic#Passenger_list).)

In [0]:
# YOUR CODE HERE

4\. Regardless of your reservations in the previous question, make "name" the index of the `DataFrame`. Use this to extract a `DataFrame` containing information about the three members of the Widener family:
  - Widener, Mr. George Dunton
  - Widener, Mr. Harry Elkins
  - Widener, Mrs. Eleanor

What became of them? Using a search engine, what else can you learn about them?


In [0]:
# YOUR CODE HERE